services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_pass
    volumes:
      - lab_data:/var/lib/postgresql/data
      - ./Data:/data
      - ./Data:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lab.com
      PGADMIN_DEFAULT_PASSWORD: admin

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./Data:/data
    environment:
      - DATABASE_URL=postgresql://lab_user:lab_pass@database:5432/lab_db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000

volumes:
  lab_data: